In [1]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_cf5705cec3fe432b93985616c8ad4532.csv"
df=pd.read_csv(url,header=None,na_values=["?"])
df.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,1,0.0,1,0.0,0.0,0.0,0.0,1,0.0,1.0,...,150.0,7.1,0.70,1.0,3.5,0.5,NaN,NaN,NaN,1
1,0,NaN,0,0.0,0.0,0.0,1.0,1,NaN,NaN,...,NaN,NaN,NaN,1.0,1.8,NaN,NaN,NaN,NaN,1
2,1,0.0,1,1.0,0.0,1.0,0.0,1,0.0,1.0,...,109.0,7.0,2.10,5.0,13.0,0.1,28.0,6.0,16.0,1
3,1,1.0,1,0.0,0.0,0.0,0.0,1,0.0,1.0,...,174.0,8.1,1.11,2.0,15.7,0.2,NaN,NaN,NaN,0
4,1,1.0,1,1.0,0.0,1.0,0.0,1,0.0,1.0,...,109.0,6.9,1.80,1.0,9.0,NaN,59.0,15.0,22.0,1

In [2]:
df=df.fillna(df.median())

In [3]:
X=df.iloc[:,0:49]
X.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,1,0.0,1,0.0,0.0,0.0,0.0,1,0.0,1.0,...,183.0,150.0,7.10,0.70,1.0,3.5,0.5,83.0,27.0,295.0
1,0,1.0,0,0.0,0.0,0.0,1.0,1,0.0,1.0,...,179.5,162.0,7.05,0.85,1.0,1.8,0.7,83.0,27.0,295.0
2,1,0.0,1,1.0,0.0,1.0,0.0,1,0.0,1.0,...,202.0,109.0,7.00,2.10,5.0,13.0,0.1,28.0,6.0,16.0
3,1,1.0,1,0.0,0.0,0.0,0.0,1,0.0,1.0,...,94.0,174.0,8.10,1.11,2.0,15.7,0.2,83.0,27.0,295.0
4,1,1.0,1,1.0,0.0,1.0,0.0,1,0.0,1.0,...,173.0,109.0,6.90,1.80,1.0,9.0,0.7,59.0,15.0,22.0

In [4]:
y=pd.DataFrame(df.iloc[:,49]).rename(columns={49:"Class"})
y.head()

   Class
0      1
1      1
2      1
3      0
4      1

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X))
X.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,0.490511,-1.453688,0.593683,-0.327693,-0.078087,-0.547003,-0.509453,0.327693,-0.254,0.765858,...,-0.326015,-0.369200,-0.153362,-0.444650,-0.968581,-0.651689,-0.303443,-0.033865,-0.242719,-0.222098
1,-2.038688,0.687906,-1.684402,-0.327693,-0.078087,-0.547003,1.962891,0.327693,-0.254,0.765858,...,-0.339694,-0.296925,-0.157785,-0.284062,-0.968581,-1.006006,-0.248372,-0.033865,-0.242719,-0.222098
2,0.490511,-1.453688,0.593683,3.051639,-0.078087,1.828143,-0.509453,0.327693,-0.254,0.765858,...,-0.251758,-0.616142,-0.162208,1.054171,1.274449,1.328313,-0.413586,-1.408916,-1.229302,-1.057430
3,0.490511,0.687906,0.593683,-0.327693,-0.078087,-0.547003,-0.509453,0.327693,-0.254,0.765858,...,-0.673851,-0.224649,-0.064899,-0.005710,-0.407824,1.891051,-0.386050,-0.033865,-0.242719,-0.222098
4,0.490511,0.687906,0.593683,3.051639,-0.078087,1.828143,-0.509453,0.327693,-0.254,0.765858,...,-0.365098,-0.616142,-0.171054,0.732995,-0.968581,0.494628,-0.248372,-0.633887,-0.806481,-1.039465

In [13]:
from sklearn.cluster import KMeans
clusterer = KMeans(n_clusters=2, random_state=0)
cluster_labels = pd.DataFrame(clusterer.fit_predict(X)).rename(columns={0:'Label'})
cluster_labels

     Label
0        1
1        1
2        1
3        1
4        1
..     ...
160      1
161      1
162      1
163      0
164      0

[165 rows x 1 columns]

In [373]:
df=pd.concat([X,y,cluster_labels],axis=1)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,Label,Class,Label
0,0.490511,-1.453688,0.593683,-0.327693,-0.078087,-0.547003,-0.509453,0.327693,-0.254,0.765858,...,-0.444650,-0.968581,-0.651689,-0.303443,-0.033865,-0.242719,-0.222098,1,1,1
1,-2.038688,0.687906,-1.684402,-0.327693,-0.078087,-0.547003,1.962891,0.327693,-0.254,0.765858,...,-0.284062,-0.968581,-1.006006,-0.248372,-0.033865,-0.242719,-0.222098,1,1,1
2,0.490511,-1.453688,0.593683,3.051639,-0.078087,1.828143,-0.509453,0.327693,-0.254,0.765858,...,1.054171,1.274449,1.328313,-0.413586,-1.408916,-1.229302,-1.057430,1,1,1
3,0.490511,0.687906,0.593683,-0.327693,-0.078087,-0.547003,-0.509453,0.327693,-0.254,0.765858,...,-0.005710,-0.407824,1.891051,-0.386050,-0.033865,-0.242719,-0.222098,1,0,1
4,0.490511,0.687906,0.593683,3.051639,-0.078087,1.828143,-0.509453,0.327693,-0.254,0.765858,...,0.732995,-0.968581,0.494628,-0.248372,-0.633887,-0.806481,-1.039465,1,1,1

In [24]:
X=df.drop(["Class"],axis=1)

In [15]:
df.groupby("Label").count().T.head()

Label   0    1
0      53  112
1      53  112
2      53  112
3      53  112
4      53  112

In [16]:
y=df[["Class"]]

In [376]:
Label=df[["Label"]]

In [381]:
y.to_csv("Class.csv")
Label.to_csv("Label.csv")

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
print(X_train.shape)
print(X_test.shape)

(99, 50)
(66, 50)

In [33]:
train=pd.concat([X_train,y_train],axis=1)
train0=train[train["Label"]==0]
train0=pd.concat([train0]*2,axis=0)
train1=train[train["Label"]==1]
train=pd.concat([train0,train1],axis=0)
train.shape

(135, 51)

In [34]:
X_train=train.drop(["Label","Class"],axis=1)
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
10,0.490511,-1.453688,0.593683,-0.327693,-0.078087,-0.547003,1.962891,0.327693,-0.254000,0.765858,...,0.889454,0.148775,-0.109130,-0.337592,1.274449,-0.339057,-0.138229,-0.033865,-0.242719,-0.222098
111,0.490511,0.687906,0.593683,-0.327693,-0.078087,-0.547003,-0.509453,0.327693,-0.254000,0.765858,...,-0.544878,-0.140327,-0.303748,0.186996,1.274449,-0.339057,5.644267,-0.033865,-0.242719,-0.222098
122,0.490511,0.687906,0.593683,-0.327693,-0.078087,1.828143,1.962891,0.327693,-0.254000,0.765858,...,0.924628,0.913693,-0.135669,-0.605238,-0.968581,-0.547479,-0.028086,-1.108905,-0.947421,-0.934675
114,0.490511,0.687906,0.593683,-0.327693,-0.078087,-0.547003,-0.509453,0.327693,-0.254000,0.765858,...,-0.826273,-0.501706,-0.162208,0.197702,-0.968581,-1.068532,0.082056,-0.833895,-0.665540,-0.937669
23,0.490511,0.687906,0.593683,-0.327693,-0.078087,-0.547003,-0.509453,0.327693,3.937004,0.765858,...,2.394135,1.112451,-0.162208,-0.626650,1.274449,1.745156,-0.000551,-0.033865,-0.242719,-0.222098

In [35]:
X_train=X_train.iloc[:,[26,40,31,35,48,28,21]]
X_train.head()

           26        40        31        35        48        28        21
10  -0.864373  0.148775  0.055624  1.425992 -0.222098  0.827329 -0.528271
111  0.833503 -0.140327 -0.840941 -0.512873 -0.222098  0.827329 -0.528271
122  0.833503  0.913693 -1.454381 -1.258590 -0.934675 -0.640513  1.892969
114  1.682441 -0.501706 -1.218443 -1.556876 -0.937669  0.827329 -0.528271
23  -0.015435  1.112451 -1.029692  0.232844 -0.222098 -0.640513  1.892969

In [38]:
y_train=train[["Class"]]

In [36]:
X_test=X_test.drop(["Label"],axis=1)
X_test=X_test.iloc[:,[26,40,31,35,48,28,21]]
X_test.head()

           26        40        31        35        48        28        21
135 -0.015435 -0.531820  0.197187  0.978562 -0.222098 -0.640513  1.892969
115 -0.864373  2.515804  0.527501  1.873422 -0.222098 -0.640513 -0.528271
131  0.833503 -0.387269 -0.746566 -0.363729 -0.222098  0.827329 -0.528271
55  -0.015435  4.286558 -0.982505 -0.363729 -0.222098 -0.640513  1.892969
95  -0.015435 -0.525797 -1.595944  0.083701  1.319822 -0.640513 -0.528271

In [132]:
from sklearn.ensemble import RandomForestClassifier
Forest=RandomForestClassifier(n_estimators=200,criterion="entropy",max_depth=1,ccp_alpha=0.01,random_state=42).fit(X_train,y_train)
Forest

/srv/conda/envs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

RandomForestClassifier(ccp_alpha=0.01, criterion='entropy', max_depth=1,
                       n_estimators=200, random_state=42)

In [133]:
from sklearn.metrics import accuracy_score
ytrain_pred=Forest.predict(X_train)
ytest_pred=Forest.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,ytrain_pred))
print("Accuracy on test data: ",accuracy_score(y_test,ytest_pred))

Accuracy on train data:  0.7185185185185186
Accuracy on test data:  0.7575757575757576

In [257]:
from sklearn.ensemble import GradientBoostingClassifier
Gradient=GradientBoostingClassifier(loss="exponential",learning_rate=0.07,criterion="mse",max_depth=1,max_features="sqrt",random_state=42).fit(X_train,y_train)
Gradient

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

GradientBoostingClassifier(criterion='mse', learning_rate=0.07,
                           loss='exponential', max_depth=1, max_features='sqrt',
                           random_state=42)

In [258]:
ytrain_pred=Gradient.predict(X_train)
ytest_pred=Gradient.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,ytrain_pred))
print("Accuracy on test data: ",accuracy_score(y_test,ytest_pred))

Accuracy on train data:  0.8222222222222222
Accuracy on test data:  0.7878787878787878

In [259]:
from sklearn.metrics import roc_auc_score
print("AUC on train data: ",roc_auc_score(y_train,ytrain_pred))
print("AUC on test data: ",roc_auc_score(y_test,ytest_pred))

AUC on train data:  0.8117088607594937
AUC on test data:  0.7576923076923078

In [273]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix: \n",confusion_matrix(y_test,ytest_pred))

Confusion matrix:
 [[16 10]
 [ 4 36]]

In [308]:
y_pred=pd.DataFrame(Forest.predict_proba(X_test)).rename(columns={0:"pred_0",1:"pred_1"})
y_pred

      pred_0    pred_1
0   0.324152  0.675848
1   0.411233  0.588767
2   0.393293  0.606707
3   0.506718  0.493282
4   0.415324  0.584676
..       ...       ...
61  0.290805  0.709195
62  0.263014  0.736986
63  0.298595  0.701405
64  0.344680  0.655320
65  0.365409  0.634591

[66 rows x 2 columns]

In [316]:
y_probs1=y_pred[["pred_1"]]

In [317]:
import numpy as np
thresholds=np.arange(0,1,0.001)

In [318]:
def to_labels(pos_probs,threshold):
    return (pos_probs >= threshold).astype('int')

In [319]:

from sklearn.metrics import f1_score
scores=[f1_score(y_test, to_labels(y_probs1,t),average="micro") for t in thresholds]

In [320]:

ix=np.argmax(scores)
print((thresholds[ix],scores[ix]))

(0.521, 0.7727272727272727)

In [321]:
y_pred["pred_0"]=np.where((y_pred.pred_0 >=0.521),1,y_pred.pred_0)
y_pred["pred_0"]=np.where((y_pred.pred_0 < 0.521),0,y_pred.pred_0)
y_pred["pred_1"]=np.where((y_pred.pred_1 >=0.521),1,y_pred.pred_1)
y_pred["pred_1"]=np.where((y_pred.pred_1 <0.521),0,y_pred.pred_1)

In [322]:
len11=len(y_pred[y_pred["pred_1"]==1])
print("The number of predicted positive cases: ",len11)

The number of predicted positive cases:  51

In [323]:

y_pred["pred_0"]=np.where((y_pred.pred_0 == y_pred.pred_1),1,y_pred.pred_0)

In [324]:
len00=len(y_pred[y_pred["pred_0"]==1])
print("The number of predicted negative cases: ",len00)

The number of predicted negative cases:  15

In [303]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(handle_unknown="ignore")
y_true=pd.DataFrame(enc.fit_transform(y_test).toarray())

In [325]:
y_pred=enc.inverse_transform(y_pred)

In [326]:
print("Accuracy on test data after adjusting the threshold: ",accuracy_score(y_test,y_pred))

Accuracy on test data after adjusting the threshold:  0.7727272727272727

In [305]:
print("AUC aftera adjusting the threshold: ",roc_auc_score(y_test,y_pred))

AUC aftera adjusting the threshold:  0.725

In [307]:
print("Confusion matrix after adjusting the threshold:\n ",confusion_matrix(y_test,y_pred))

Confusion matrix after adjusting the threshold:
  [[13 13]
 [ 2 38]]

In [369]:
from sklearn import svm
SVM=svm.SVC(C=0.5,kernel="linear",decision_function_shape="ovo",random_state=42).fit(X_train,y_train)
SVM

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

SVC(C=0.5, cache_size=150, decision_function_shape='ovo', kernel='linear',
    random_state=42)

In [370]:
ytrain_pred=SVM.predict(X_train)
ytest_pred=SVM.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,ytrain_pred))
print("Accuracy on test data: ",accuracy_score(y_test,ytest_pred))

Accuracy on train data:  0.7333333333333333
Accuracy on test data:  0.7727272727272727