In [19]:
pip install imbalanced-learn

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
     |████████████████████████████████| 167 kB 3.0 MB/s eta 0:00:01
Requirement already satisfied: scipy>=0.19.1 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: joblib>=0.11 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from imbalanced-learn) (0.17.0)
Requirement already satisfied: numpy>=1.13.3 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from imbalanced-learn) (1.19.2)
Requirement already satisfied: scikit-learn>=0.23 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from imbalanced-learn) (0.23.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /srv/conda/envs/notebook/lib/python3.6/site-packages (from scikit-learn>=0.23->imbalanced-learn) (2.1.0)
Installing collected packages: imbalanced-learn
Successfully installed imbalanced-learn-0.7.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_ed1d1e1872004faf87fa9b69405df7ef.csv"
df=pd.read_csv(url,header=None,na_values=["?"])
df.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,diaporthe-stem-canker,6.0,0.0,2.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
1,diaporthe-stem-canker,4.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2,diaporthe-stem-canker,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3,diaporthe-stem-canker,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
4,diaporthe-stem-canker,6.0,0.0,2.0,1.0,0.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
df.shape

(307, 36)

In [6]:
df=df.rename(columns={0:"Class"})
df.groupby("Class")["Class"].count()

Class
2-4-d-injury                    1
alternarialeaf-spot            40
anthracnose                    20
bacterial-blight               10
bacterial-pustule              10
brown-spot                     40
brown-stem-rot                 20
charcoal-rot                   10
cyst-nematode                   6
diaporthe-pod-&-stem-blight     6
diaporthe-stem-canker          10
downy-mildew                   10
frog-eye-leaf-spot             40
herbicide-injury                4
phyllosticta-leaf-spot         10
phytophthora-rot               40
powdery-mildew                 10
purple-seed-stain              10
rhizoctonia-root-rot           10
Name: Class, dtype: int64

In [3]:
df.isna().any()

0     False
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12    False
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
dtype: bool

In [7]:
df.dtypes

Class     object
1        float64
2        float64
3        float64
4        float64
5        float64
6        float64
7        float64
8        float64
9        float64
10       float64
11       float64
12         int64
13       float64
14       float64
15       float64
16       float64
17       float64
18       float64
19       float64
20       float64
21       float64
22       float64
23       float64
24       float64
25       float64
26       float64
27       float64
28       float64
29       float64
30       float64
31       float64
32       float64
33       float64
34       float64
35       float64
dtype: object

In [8]:
df=df.fillna(df.median())
df.isna().any()

Class    False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
30       False
31       False
32       False
33       False
34       False
35       False
dtype: bool

In [9]:
df1=df[df["Class"]=="2-4-d-injury"]
df1

,Class,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
302,2-4-d-injury,4.0,0.0,2.0,1.0,0.0,2.0,2.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df2=df[df["Class"]=="herbicide-injury"]
df2

,Class,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
303,herbicide-injury,1.0,1.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
304,herbicide-injury,0.0,1.0,2.0,0.0,0.0,0.0,3.0,1.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
305,herbicide-injury,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
306,herbicide-injury,1.0,1.0,2.0,0.0,0.0,1.0,3.0,1.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
sub_df=pd.concat([df1,df2],axis=0)
df=df.drop(index=sub_df.index)
df.shape

(302, 36)

In [12]:
y=df[["Class"]]
X=df.drop(["Class"],axis=1)

In [77]:
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif

# feature extraction. We are going to output the selection scores for all features and select the features with the highest scores.
test = SelectKBest(score_func=mutual_info_classif, k="all")
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
# summarize scores
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

      scores
14  0.911384
21  0.866201
12  0.802854
28  0.746963
20  0.703932
13  0.630897
27  0.624460
18  0.584773
2   0.571642
7   0.500489
0   0.499606
10  0.487591
3   0.452522
6   0.443118
32  0.400729
25  0.387499
23  0.370337
29  0.368083
22  0.363335
34  0.351639
30  0.321216
11  0.313867
17  0.289188
31  0.264532
15  0.255678
1   0.204869
33  0.164534
26  0.159807
9   0.150646
4   0.114858
16  0.083414
19  0.070306
5   0.034083
8   0.020935
24  0.000000

In [17]:
X_scores=scores[scores["scores"]>=0.5]
len(X_scores)

11

In [18]:
X=X.iloc[:,X_scores.index]
X.head()

    15   29   13   22   21   28   3    11   14   19   8
0  2.0  4.0  0.0  1.0  3.0  0.0  2.0  1.0  2.0  1.0  1.0
1  2.0  4.0  0.0  1.0  3.0  0.0  2.0  1.0  2.0  1.0  2.0
2  2.0  4.0  0.0  0.0  3.0  0.0  2.0  1.0  2.0  1.0  2.0
3  2.0  4.0  0.0  0.0  3.0  0.0  2.0  1.0  2.0  1.0  2.0
4  2.0  4.0  0.0  1.0  3.0  0.0  2.0  1.0  2.0  1.0  1.0

In [20]:
from imblearn.ensemble import BalancedRandomForestClassifier
import numpy as np
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [40]:
BForest=BalancedRandomForestClassifier(n_estimators=200,criterion="entropy",max_depth=7,min_samples_split=3,
                                       min_samples_leaf=1,max_features="sqrt",bootstrap=False,
                                       sampling_strategy="auto",replacement=True,n_jobs=-1,warm_start=False,
                                       random_state=0)
scores=cross_val_score(BForest,X,np.asarray(y).reshape(y.shape[0],),cv=12)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=12.
  % (min_groups, self.n_splits)), UserWarning)

Accuracy:  0.8383333333333333 +/- 0.06589531573961388

In [57]:
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.naive_bayes import GaussianNB
BBagging=BalancedBaggingClassifier(base_estimator=GaussianNB(),n_estimators=26,sampling_strategy="all",n_jobs=-1,
                                   random_state=0)
scores=cross_val_score(BBagging,X,np.asarray(y).reshape(y.shape[0],),cv=10)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)

Accuracy:  0.8053763440860214 +/- 0.07348894032190012

Let's see if including a few more predictor variables will provide the model more information and therefore improve performance.

In [69]:
X=df.drop(["Class"],axis=1)
X_scores=scores[scores["scores"]>=0.45]
len(X_scores)

13

In [70]:
BForest=BalancedRandomForestClassifier(n_estimators=200,criterion="entropy",max_depth=7,min_samples_split=3,
                                       min_samples_leaf=1,max_features="sqrt",bootstrap=False,
                                       sampling_strategy="auto",replacement=True,n_jobs=-1,warm_start=False,
                                       random_state=0)
scores=cross_val_score(BForest,X,np.asarray(y).reshape(y.shape[0],),cv=12)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=12.
  % (min_groups, self.n_splits)), UserWarning)

Accuracy:  0.9206410256410257 +/- 0.036120870577212735

In [71]:
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.naive_bayes import GaussianNB
BBagging=BalancedBaggingClassifier(base_estimator=GaussianNB(),n_estimators=26,sampling_strategy="all",n_jobs=-1,
                                   random_state=0)
scores=cross_val_score(BBagging,X,np.asarray(y).reshape(y.shape[0],),cv=10)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)

Accuracy:  0.8480645161290322 +/- 0.04326283654342753

By increasing the number of variables from 11 to 13, both models' performances were improved. The BalancedRandomForest model's performance jumped by almost 10%. The extra imformation carried by the 2 additional variables were crucial.

Let's see if we can further improve the model's performance by simply giving the  models more information.

In [78]:
X=df.drop(["Class"],axis=1)
X_scores=scores[scores["scores"]>=0.4]
len(X_scores)

15

In [79]:
BForest=BalancedRandomForestClassifier(n_estimators=200,criterion="entropy",max_depth=7,min_samples_split=3,
                                       min_samples_leaf=1,max_features="sqrt",bootstrap=False,
                                       sampling_strategy="auto",replacement=True,n_jobs=-1,warm_start=False,
                                       random_state=0)
scores=cross_val_score(BForest,X,np.asarray(y).reshape(y.shape[0],),cv=12)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=12.
  % (min_groups, self.n_splits)), UserWarning)

Accuracy:  0.9206410256410257 +/- 0.036120870577212735

In [80]:
BBagging=BalancedBaggingClassifier(base_estimator=GaussianNB(),n_estimators=26,sampling_strategy="all",n_jobs=-1,
                                   random_state=0)
scores=cross_val_score(BBagging,X,np.asarray(y).reshape(y.shape[0],),cv=10)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)

Accuracy:  0.8480645161290322 +/- 0.04326283654342753

However, by increasing the number of variables further to 15, both models showed no more further improvements. It seems that we have maxed out.

Plot the confusion matrix for the BalancedRandomForestModel.

In [82]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(BForest, X,np.asarray(y).reshape(y.shape[0],), cv=12)
print("Confusion matrix: \n",confusion_matrix(y,y_pred))

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=12.
  % (min_groups, self.n_splits)), UserWarning)

Confusion matrix:
 [[38  0  0  0  1  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  9  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 36  0  0  0  0  0  0  1  3  0  0  0  0]
 [ 0  0  0  0  0 19  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0]
 [11  0  0  0  1  0  0  0  1  0  0 26  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 40  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10]]

In [83]:
y.groupby("Class")["Class"].count()

Class
alternarialeaf-spot            40
anthracnose                    20
bacterial-blight               10
bacterial-pustule              10
brown-spot                     40
brown-stem-rot                 20
charcoal-rot                   10
cyst-nematode                   6
diaporthe-pod-&-stem-blight     6
diaporthe-stem-canker          10
downy-mildew                   10
frog-eye-leaf-spot             40
phyllosticta-leaf-spot         10
phytophthora-rot               40
powdery-mildew                 10
purple-seed-stain              10
rhizoctonia-root-rot           10
Name: Class, dtype: int64

Except for "phytophthora-rot", "brown-spot", the BalancedRandomForest model did pretty well predicting the other classes. For some classes, "bacterial-blight", "charcoal-rot", "cyst-nematode", "diaporthe-pod-&-stem-blight", "diaporthe-stem-canker", "downy-mildew", "phyllosticta-leaf-spot", "phytophthora-rot", "powdery-mildew", "purple-seed-stain", "rhizoctonia-root-rot ", the model has a 100% sensitivity.

I filtered out two classes that have only 1 and 4 instances, respectively. How would the model's performance be different if I include those two "outlier" classes.

In [84]:
url="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_ed1d1e1872004faf87fa9b69405df7ef.csv"
df=pd.read_csv(url,header=None,na_values=["?"])

In [85]:
df=df.fillna(df.median())

In [86]:
df=df.rename(columns={0:"Class"})

In [87]:
X=df.drop(["Class"],axis=1)
y=df[["Class"]]

In [88]:
test = SelectKBest(score_func=mutual_info_classif, k="all")
fit = test.fit(X, np.asarray(y).reshape(y.shape[0],))
features = fit.transform(X)
# summarize scores
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

      scores
12  0.881126
14  0.878724
28  0.820153
21  0.815963
27  0.661871
13  0.658914
10  0.635832
20  0.621853
18  0.606379
2   0.589287
7   0.581172
0   0.508378
3   0.447271
11  0.417794
29  0.416512
6   0.399195
30  0.369613
25  0.351457
17  0.351428
32  0.326071
22  0.315952
34  0.306522
23  0.288452
31  0.284849
1   0.268429
33  0.222592
15  0.221080
9   0.189969
26  0.155433
16  0.108255
5   0.108154
19  0.083814
8   0.074142
4   0.064357
24  0.047720

I will use 13 predictor variables as well.

In [91]:
X_scores=scores[scores["scores"]>0.42]
len(X_scores)

13

In [92]:
X=X.iloc[:,X_scores.index]

In [93]:
BForest=BalancedRandomForestClassifier(n_estimators=200,criterion="entropy",max_depth=7,min_samples_split=3,
                                       min_samples_leaf=1,max_features="sqrt",bootstrap=False,
                                       sampling_strategy="auto",replacement=True,n_jobs=-1,warm_start=False,
                                       random_state=0)
scores=cross_val_score(BForest,X,np.asarray(y).reshape(y.shape[0],),cv=12)
print("Accuracy: ",scores.mean(),"+/-",scores.std())

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/model_selection/_split.py:672: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=12.
  % (min_groups, self.n_splits)), UserWarning)

Accuracy:  0.7525641025641026 +/- 0.0759965568962966

As shown, if the two "outlier" classes were not dropped, with the same number of predictor variables and the same hyper-parameter values, the BalancedRandomForest model's performance is about 17% lower. By simply dropping those two outlier classes, I improved the model's performance by 17%.

Let's analyze those two outlier classes.

In [104]:
sub_X=sub_df.drop(["Class"],axis=1)

In [105]:
sub_y=sub_df[["Class"]]

In [106]:
sub_X.shape

(5, 35)

In [107]:
test = SelectKBest(score_func=mutual_info_classif, k="all")
fit = test.fit(sub_X, np.asarray(sub_y).reshape(sub_y.shape[0],))
features = fit.transform(sub_X)
# summarize scores
set_printoptions(precision=3)

scores=fit.scores_
scores=pd.DataFrame(scores)
scores=scores.rename(columns={0:"scores"})
scores=scores.sort_values(by=["scores"],ascending=False)
scores

          scores
9   1.500000e+00
10  1.500000e+00
11  1.500000e+00
18  1.500000e+00
2   5.833333e-01
7   5.833333e-01
34  1.250000e-01
16  1.250000e-01
27  1.250000e-01
1   1.250000e-01
33  1.110223e-16
28  1.110223e-16
26  1.110223e-16
25  1.110223e-16
23  1.110223e-16
22  1.110223e-16
0   1.110223e-16
15  1.110223e-16
12  1.110223e-16
3   1.110223e-16
4   1.110223e-16
5   1.110223e-16
14  1.110223e-16
17  1.110223e-16
13  1.110223e-16
24  0.000000e+00
8   0.000000e+00
21  0.000000e+00
20  0.000000e+00
29  0.000000e+00
30  0.000000e+00
31  0.000000e+00
32  0.000000e+00
19  0.000000e+00
6   0.000000e+00

In [108]:
sub_scores=scores[scores["scores"]>=1.5]
len(sub_scores)

4

In [109]:
sub_X=sub_X.iloc[:,sub_scores.index]
sub_X

      10   11  12   19
302  1.0  0.0   1  1.0
303  1.0  1.0   1  1.0
304  1.0  1.0   1  1.0
305  1.0  1.0   1  1.0
306  1.0  1.0   1  1.0

In [110]:
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [111]:
clusterer = KMeans(n_clusters=2, random_state=0)
cluster_labels = clusterer.fit_predict(sub_X)

In [114]:
label=pd.DataFrame(cluster_labels).rename(columns={0:"Label"})

In [116]:
sub_X=sub_X.reset_index(drop=True)
sub_y=sub_y.reset_index(drop=True)

In [117]:
outliers=pd.concat([sub_X,sub_y,label],axis=1)
outliers

    10   11  12   19             Class  Label
0  1.0  0.0   1  1.0      2-4-d-injury      1
1  1.0  1.0   1  1.0  herbicide-injury      0
2  1.0  1.0   1  1.0  herbicide-injury      0
3  1.0  1.0   1  1.0  herbicide-injury      0
4  1.0  1.0   1  1.0  herbicide-injury      0

KMeans clustering with K=2 perfectly labeled the two outlier classes.