In [1]:
import pandas as pd
url2="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_aa4ff181881749dd8669f34e82c87c01.csv"
df2=pd.read_csv(url2,header=None)
df2.head()

    0  1   2  3   4   5   6   7   8  9
0  55  0  81  0  -6  11  25  88  64  4
1  56  0  96  0  52  -4  40  44   4  4
2  50 -1  89 -7  50   0  39  40   2  1
3  53  9  79  0  42  -2  25  37  12  4
4  55  2  82  0  54  -6  26  28   2  1

In [2]:
df2.shape

(14500, 10)

In [3]:
df2=df2.rename(columns={9:"Class"})
df2.head()

    0  1   2  3   4   5   6   7   8  Class
0  55  0  81  0  -6  11  25  88  64      4
1  56  0  96  0  52  -4  40  44   4      4
2  50 -1  89 -7  50   0  39  40   2      1
3  53  9  79  0  42  -2  25  37  12      4
4  55  2  82  0  54  -6  26  28   2      1

In [4]:
X_test=df2.drop(["Class"],axis=1)
y_test=df2[["Class"]]

In [5]:
y_test.groupby("Class")["Class"].count()

Class
1    11478
2       13
3       39
4     2155
5      809
6        4
7        2
Name: Class, dtype: int64

In [6]:
y_test.groupby("Class")["Class"].count()/len(y_test)

Class
1    0.791586
2    0.000897
3    0.002690
4    0.148621
5    0.055793
6    0.000276
7    0.000138
Name: Class, dtype: float64

In [7]:
url1="https://bd29ee0e-54ab-4daa-9671-d153865d1620.usrfiles.com/ugd/bd29ee_9d91340770aa4a1483cef85ef184b206.csv"
df1=pd.read_csv(url1,header=None)
df1.head()

    0   1   2  3   4   5   6   7   8  9
0  50  21  77  0  28   0  27  48  22  2
1  55   0  92  0   0  26  36  92  56  4
2  53   0  82  0  52  -5  29  30   2  1
3  37   0  76  0  28  18  40  48   8  1
4  37   0  79  0  34 -26  43  46   2  1

In [8]:
df1.shape

(43500, 10)

In [9]:
df1=df1.rename(columns={9:"Class"})
df1.head()

    0   1   2  3   4   5   6   7   8  Class
0  50  21  77  0  28   0  27  48  22      2
1  55   0  92  0   0  26  36  92  56      4
2  53   0  82  0  52  -5  29  30   2      1
3  37   0  76  0  28  18  40  48   8      1
4  37   0  79  0  34 -26  43  46   2      1

In [10]:
X_train=df1.drop(["Class"],axis=1)
y_train=df1[["Class"]]

In [11]:
y_train.groupby("Class")["Class"].count()

Class
1    34108
2       37
3      132
4     6748
5     2458
6        6
7       11
Name: Class, dtype: int64

In [12]:
y_train.groupby("Class")["Class"].count()/len(y_train)

Class
1    0.784092
2    0.000851
3    0.003034
4    0.155126
5    0.056506
6    0.000138
7    0.000253
Name: Class, dtype: float64

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=pd.DataFrame(scaler.fit_transform(X_train))
X_train.head()

,0,1,2,3,4,5,6,7,8
0,0.142849,0.271367,-0.936360,-0.006408,-0.300822,-0.007233,-0.766977,-0.135110,0.313294
1,0.550930,0.002625,0.747425,-0.006408,-1.590956,0.137626,-0.081806,1.914930,1.638928
2,0.387697,0.002625,-0.375098,-0.006408,0.805008,-0.035091,-0.614717,-0.973762,-0.466490
3,-0.918161,0.002625,-1.048612,-0.006408,-0.300822,0.093054,0.222715,-0.135110,-0.232555
4,-0.918161,0.002625,-0.711855,-0.006408,-0.024364,-0.152092,0.451105,-0.228293,-0.466490

In [14]:
X_test=pd.DataFrame(scaler.fit_transform(X_test))
X_test.head()

,0,1,2,3,4,5,6,7,8
0,0.557315,-0.006946,-0.492030,-0.014676,-1.886377,0.027786,-0.931508,1.746157,1.966424
1,0.639320,-0.006946,1.196168,-0.014676,0.807578,-0.021468,0.218920,-0.321336,-0.385564
2,0.147288,-0.019866,0.408342,-0.424818,0.714683,-0.008334,0.142225,-0.509290,-0.463963
3,0.393304,0.109336,-0.717124,-0.014676,0.343103,-0.014901,-0.931508,-0.650256,-0.071965
4,0.557315,0.018895,-0.379484,-0.014676,0.900473,-0.028035,-0.854813,-1.073152,-0.463963

In [15]:
from sklearn.multiclass import OneVsOneClassifier
from sklearn import svm
import numpy as np

model=OneVsOneClassifier(svm.SVC(C=8,gamma="auto",random_state=0)).fit(X_train, np.asarray(y_train).reshape(y_train.shape[0],))
model

OneVsOneClassifier(estimator=SVC(C=8, gamma='auto', random_state=0))

In [55]:
from sklearn.metrics import accuracy_score
train_pred=model.predict(X_train)
test_pred=model.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,train_pred))
print("Accuracy on test data: ",accuracy_score(y_test,test_pred))

Accuracy on train data:  0.9996551724137931
Accuracy on test data:  0.9986206896551724

In [56]:
from sklearn.metrics import f1_score
print("F1 socre for train data: ",f1_score(y_train,train_pred,average="micro"))
print("F1 score for test data: ",f1_score(y_test,test_pred,average="micro"))

F1 socre for train data:  0.9996551724137931
F1 score for test data:  0.9986206896551724

In [57]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix for train data: \n",confusion_matrix(y_train,train_pred))
print("Confusion matrix for test data: \n",confusion_matrix(y_test,test_pred))

Confusion matrix for train data:
 [[34108     0     0     0     0     0     0]
 [    2    33     0     2     0     0     0]
 [   11     0   121     0     0     0     0]
 [    0     0     0  6748     0     0     0]
 [    0     0     0     0  2458     0     0]
 [    0     0     0     0     0     6     0]
 [    0     0     0     0     0     0    11]]
Confusion matrix for test data:
 [[11476     0     1     0     0     0     1]
 [    1     9     0     3     0     0     0]
 [    7     0    32     0     0     0     0]
 [    0     0     0  2155     0     0     0]
 [    2     0     0     0   807     0     0]
 [    3     0     0     0     0     1     0]
 [    2     0     0     0     0     0     0]]

In [33]:
from sklearn.ensemble import RandomForestClassifier
model=OneVsOneClassifier(RandomForestClassifier(random_state=0)).fit(X_train, np.asarray(y_train).reshape(y_train.shape[0],))
model

OneVsOneClassifier(estimator=RandomForestClassifier(random_state=0))

In [34]:
train_pred=model.predict(X_train)
test_pred=model.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,train_pred))
print("Accuracy on test data: ",accuracy_score(y_test,test_pred))

Accuracy on train data:  1.0
Accuracy on test data:  0.9997241379310344

In [35]:
print("F1 socre for train data: ",f1_score(y_train,train_pred,average="micro"))
print("F1 score for test data: ",f1_score(y_test,test_pred,average="micro"))

F1 socre for train data:  1.0
F1 score for test data:  0.9997241379310344

In [36]:
print("Confusion matrix for train data: \n",confusion_matrix(y_train,train_pred))
print("Confusion matrix for test data: \n",confusion_matrix(y_test,test_pred))

Confusion matrix for train data:
 [[34108     0     0     0     0     0     0]
 [    0    37     0     0     0     0     0]
 [    0     0   132     0     0     0     0]
 [    0     0     0  6748     0     0     0]
 [    0     0     0     0  2458     0     0]
 [    0     0     0     0     0     6     0]
 [    0     0     0     0     0     0    11]]
Confusion matrix for test data:
 [[11475     0     3     0     0     0     0]
 [    0    12     0     1     0     0     0]
 [    0     0    39     0     0     0     0]
 [    0     0     0  2155     0     0     0]
 [    0     0     0     0   809     0     0]
 [    0     0     0     0     0     4     0]
 [    0     0     0     0     0     0     2]]

In [23]:
from sklearn.ensemble import GradientBoostingClassifier
model=OneVsOneClassifier(GradientBoostingClassifier(random_state=0)).fit(X_train, np.asarray(y_train).reshape(y_train.shape[0],))
model

OneVsOneClassifier(estimator=GradientBoostingClassifier(random_state=0))

In [24]:
from sklearn.metrics import accuracy_score
train_pred=model.predict(X_train)
test_pred=model.predict(X_test)
print("Accuracy on train data: ",accuracy_score(y_train,train_pred))
print("Accuracy on test data: ",accuracy_score(y_test,test_pred))

Accuracy on train data:  1.0
Accuracy on test data:  0.9999310344827587

In [60]:
print("F1 socre for train data: ",f1_score(y_train,train_pred,average="micro"))
print("F1 score for test data: ",f1_score(y_test,test_pred,average="micro"))

F1 socre for train data:  1.0
F1 score for test data:  0.9999310344827587

In [61]:
print("Confusion matrix for train data: \n",confusion_matrix(y_train,train_pred))
print("Confusion matrix for test data: \n",confusion_matrix(y_test,test_pred))

Confusion matrix for train data:
 [[34108     0     0     0     0     0     0]
 [    0    37     0     0     0     0     0]
 [    0     0   132     0     0     0     0]
 [    0     0     0  6748     0     0     0]
 [    0     0     0     0  2458     0     0]
 [    0     0     0     0     0     6     0]
 [    0     0     0     0     0     0    11]]
Confusion matrix for test data:
 [[11477     0     0     0     1     0     0]
 [    0    13     0     0     0     0     0]
 [    0     0    39     0     0     0     0]
 [    0     0     0  2155     0     0     0]
 [    0     0     0     0   809     0     0]
 [    0     0     0     0     0     4     0]
 [    0     0     0     0     0     0     2]]

#### Best result: 99.993% accuracy on test data!